# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

#networks:
#  byfn:

services:
  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=multipeer_default
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    extra_hosts:
      - "orderer.example.com:10.108.233.153"
      - "peer0.org1.example.com:10.108.233.160"
      # - "peer1.org1.example.com:10.108.233.156"
      - "peer0.org2.example.com:10.108.233.163"
      - "peer0.org3.example.com:10.108.233.153"
      # - "peer1.org2.example.com:10.108.233.158"
#    networks:
#      - byfn

#   peer1.org3.example.com:
#     container_name: peer1.org3.example.com
#     image: hyperledger/fabric-peer
#     environment:
#       - CORE_PEER_ID=peer1.org3.example.com
#       - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
#       - CORE_PEER_CHAINCODEADDRESS=peer1.org3.example.com:7052
#       - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
#       - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:7051
#       - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:7051
#       - CORE_PEER_LOCALMSPID=Org3MSP

#       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
#       # the following setting starts chaincode containers on the same
#       # bridge network as the peers
#       # https://docs.docker.com/compose/networking/
#       - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=multipeer_default
#       #- CORE_LOGGING_LEVEL=ERROR
#       - CORE_LOGGING_LEVEL=DEBUG
#       - CORE_PEER_TLS_ENABLED=true
#       - CORE_PEER_GOSSIP_USELEADERELECTION=true
#       - CORE_PEER_GOSSIP_ORGLEADER=false
#       - CORE_PEER_PROFILE_ENABLED=true
#       - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
#       - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
#       - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
#     working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#     command: peer node start
#     volumes:
#         - /var/run/:/host/var/run/
#         - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/etc/hyperledger/fabric/msp
#         - ./crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/etc/hyperledger/fabric/tls
#     ports:
#       - 8051:7051
#       - 8052:7052
#       - 8053:7053
#     extra_hosts:
#       - "orderer.example.com:10.108.233.159"
#       - "peer0.org1.example.com:10.108.233.159"
#       - "peer1.org1.example.com:10.108.233.156"
#       - "peer0.org2.example.com:10.108.233.161"
#       - "peer1.org2.example.com:10.108.233.158"
# #    networks:
# #      - byfn



